### ISSUE TITLE
Crash cause by buttons 

### ISSUE THREAD

**Issue by gregorybel** [monkey-r/ruffy#7]
Just after app start, buttons menu and validate are enabled and if one click it without connection then app crashes.

**Comment by gregorybel** [comment]
logcat:

05-26 22:56:38.417 28129-28129/? I/InstantRun: starting instant run server: is main process
05-26 22:56:38.450 28129-28129/? I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
05-26 22:56:38.485 28129-28129/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-26 22:56:38.514 28129-28141/? I/art: humin current process: org.monkey.d.ruffy.ruffy
05-26 22:56:38.515 28129-28141/? I/art: current process_level is : 0
05-26 22:56:38.550 28129-28129/? I/HwSecImmHelper: mSecurityInputMethodService is null
05-26 22:56:38.591 28129-28191/? I/OpenGLRenderer: Initialized EGL, version 1.4
05-26 22:56:41.439 28129-28129/org.monkey.d.ruffy.ruffy I/Process: Sending signal. PID: 28129 SIG: 9

**Comment by SandraK82** [comment]
fixed in https://github.com/monkey-r/ruffy/commit/c226cdf9e6e0503f738031ace77e89ed17a760c7
